[project]
name = "dsml-ai"
version = "0.1.0"
description = "DS + ML playground with modular stacks"
authors = [
    {name = "pitcany", email = "pitcany@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["data science", "machine learning", "deep learning", "bayesian", "time series", "visualization"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "<2.0"
pandas = "^2.2"
scipy = "^1.12"
scikit-learn = "^1.4"
matplotlib = "^3.8"
seaborn = "^0.12"
jupyterlab = "^4.0"
notebook = "^7.0"
ipykernel = "^6.29"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
black = "^25.9.0"

[tool.poetry]
package-mode = true
packages = [
  { include = "dsml_ai", from = "src" }
]

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"
